# docker run -d --rm --name mongo -p 27017:27017 -v mongodbdata:/data/db mongo

# Define FileVersion
version: '28.4'

# List services to run
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672   # Broker
      - 15672:15672 # Portal 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    hostname: rabbitmq # Reason: Associates how RMQ stores data internally. If not defined, you'd lose data every startup

volumes:
  mongodbdata:
  rabbitmq_data: